/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AgentCard: typeof import('./components/AgentCard.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    OrClient: typeof import('./components/OrClient.vue')['default']
    OrClientAgentCard: typeof import('./components/OrClientAgentCard.vue')['default']
    OrClientAgentList: typeof import('./components/OrClientAgentList.vue')['default']
    OrClientAgentListCard: typeof import('./components/OrClientAgentListCard.vue')['default']
    OrClientAgents: typeof import('./components/OrClientAgents.vue')['default']
    OrClientChat: typeof import('./components/OrClientChat.vue')['default']
    OrClientChatContent: typeof import('./components/OrClientChatContent.vue')['default']
    OrClientChatContentEdit: typeof import('./components/OrClientChatContentEdit.vue')['default']
    OrClientChatHistory: typeof import('./components/OrClientChatHistory.vue')['default']
    OrClientChatHistoryCard: typeof import('./components/OrClientChatHistoryCard.vue')['default']
    OrClientChatInput: typeof import('./components/OrClientChatInput.vue')['default']
    OrClientChatMessage: typeof import('./components/OrClientChatMessage.vue')['default']
    OrClientChatMessageCard: typeof import('./components/OrClientChatMessageCard.vue')['default']
    OrClientChatMessageList: typeof import('./components/OrClientChatMessageList.vue')['default']
    OrClientChatMessageListCard: typeof import('./components/OrClientChatMessageListCard.vue')['default']
    OrClientChatSidebar: typeof import('./components/OrClientChatSidebar.vue')['default']
    OrClientChatTool: typeof import('./components/OrClientChatTool.vue')['default']
    OrClientConfig: typeof import('./components/OrClientConfig.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
